import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {verifyPublishingSettings} from '../scripts/publish-settings.mjs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const workflow = `# Generated by scripts/generate-publish-caller.mjs; review changes before merging.
name: Publish verified npm beta
on:
  workflow_dispatch:
    inputs:
      release-id:
        description: 'Numeric ID of the staged draft prerelease'
        required: true
        type: string
      version:
        description: 'Reviewed beta version staged as draft release vVERSION'
        required: true
        type: string
      source-sha:
        description: 'Full tested commit SHA; must be current main'
        required: true
        type: string
      artifact-sha256:
        description: 'SHA-256 of the exact independently verified candidate.tgz'
        required: true
        type: string
permissions: {}
jobs:
  publish:
    if: github.repository == 'jdorado/ez-library' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      checks: read
      actions: read
      pull-requests: read
      id-token: write
    uses: jdorado/ez-agents/.github/workflows/npm-beta-shared.yml@fed05b9c88a5d96a801436a36983254758f03389
    with:
      package: '@jc_stack/ez-library'
      publisher-sha: 'fed05b9c88a5d96a801436a36983254758f03389'
      required-checks: '["verify (22)","verify (24)","docker"]'
      release-id: \${{ inputs.release-id }}
      version: \${{ inputs.version }}
      source-sha: \${{ inputs.source-sha }}
      artifact-sha256: \${{ inputs.artifact-sha256 }}
`;

test('publishing settings match the public trusted-publisher workflow', () => {
  const settings = verifyPublishingSettings(pkg, workflow);
  assert.equal(settings.package.private, false);
  assert.equal(settings.package.access, 'public');
  assert.equal(settings.package.tag, 'latest');
  assert.equal(settings.workflow.package, pkg.name);
});

test('publishing settings reject private packages', () => {
  assert.throws(
    () => verifyPublishingSettings({...pkg, private: true}, workflow),
    /must not set private:true/,
  );
});

test('publishing settings reject non-public npm access', () => {
  assert.throws(
    () => verifyPublishingSettings({...pkg, publishConfig: {...pkg.publishConfig, access: 'restricted'}}, workflow),
    /publishConfig\.access must be public/,
  );
});

for (const [name, change] of [
  ['commented repository guard', text => text.replace('    if:', '    # if:')],
  ['weakened repository guard', text => text.replace("github.ref == 'refs/heads/main'", "github.ref == 'refs/heads/main' || true")],
  ['commented workflow pin', text => text.replace('    uses:', '    # uses:')],
  ['missing OIDC permission', text => text.replace('      id-token: write', '')],
  ['OIDC permission under inputs', text => text.replace('      id-token: write\n', '').replace('    with:', '    with:\n      id-token: write')],
  ['duplicate job guard', text => text.replace('    permissions:', '    if: true\n    permissions:')],
  ['missing artifact input', text => text.split('\n').filter(line => !line.includes('artifact-sha256:')).join('\n')],
  ['unpinned shared workflow', text => text.replace(/npm-beta-shared.yml@[a-f0-9]{40}/, 'npm-beta-shared.yml@main')],
  ['mismatched publisher pin', text => text.replace(/publisher-sha: '[a-f0-9]{40}'/, "publisher-sha: '" + 'a'.repeat(40) + "'")],
  ['wrong package input', text => text.replace("package: '@jc_stack/ez-library'", "package: '@jc_stack/other'")],
]) {
  test('publishing settings reject ' + name, () => {
    assert.throws(() => verifyPublishingSettings(pkg, change(workflow)));
  });
}

test('generated caller accepts comments, blank lines, CRLF and matching pin updates', () => {
  const changed = workflow.replaceAll('fed05b9c88a5d96a801436a36983254758f03389', 'a'.repeat(40));
  const settings = verifyPublishingSettings(pkg, '# uses: jdorado/ez-agents/.github/workflows/npm-beta-shared.yml@' + 'b'.repeat(40) + '\n\n' + changed.replaceAll('\n', '  \r\n'));
  assert.equal(settings.workflow.publisherSha, 'a'.repeat(40));
});

for (const [name, changed] of [
  ['wrong tag', {...pkg, publishConfig: {...pkg.publishConfig, tag: 'beta'}}],
  ['wrong repository', {...pkg, repository: {url: 'git+https://github.com/other/ez-library.git'}}],
]) {
  test('publishing settings reject ' + name, () => {
    assert.throws(() => verifyPublishingSettings(changed, workflow));
  });
}
